/**
 * Job Notification Helper
 * Auto-send notifications for job-related events
 */
import notificationApiService from '../services/api/NotificationApiService';

export class JobNotificationHelper {
    /**
     * Tự động gửi thông báo khi có job mới được đăng
     * @param {object} jobData - Job data
     * @param {string} employerId - Employer ID
     */
    static async autoNotifyJobPosted(jobData, employerId) {
        try {
            console.log('Auto-sending job posted notification...', { jobId: jobData.id, employerId });
            
            // Sử dụng createNotification thay vì sendSystemNotification để đơn giản hơn
            const response = await notificationApiService.createNotification({
                user_id: employerId, // Tạm thời gửi cho chính employer để test
                type: 'job_posted',
                title: `Job Posted Successfully`,
                message: `Your job "${jobData.title}" has been posted successfully and is now visible to candidates.`,
                data: {
                    jobId: jobData.id,
                    jobTitle: jobData.title,
                    company: jobData.company,
                    location: jobData.location,
                    salaryMin: jobData.salaryMin,
                    salaryMax: jobData.salaryMax,
                    action: 'view_job',
                    auto_generated: true,
                    timestamp: new Date().toISOString()
                }
            });

            console.log('Auto job notification sent successfully:', response);
            return response;
        } catch (error) {
            console.error('Failed to auto-send job notification:', error);
            // Không throw error để không ảnh hưởng đến job creation
            return null;
        }
    }

    /**
     * Tự động gửi thông báo khi có ứng viên apply
     * @param {object} applicationData - Application data
     */
    static async autoNotifyJobApplication(applicationData) {
        try {
            console.log('🔄 Auto-sending application notification...');
            
            const response = await notificationApiService.createNotification({
                recipient_id: applicationData.employerId,
                recipient_type: 'employer',
                title: `📝 Ứng viên mới ứng tuyển`,
                message: `${applicationData.candidateName || 'Một ứng viên'} đã ứng tuyển vào vị trí ${applicationData.jobTitle}`,
                type: 'application_status',
                sender_id: applicationData.candidateId,
                sender_type: 'candidate',
                data: {
                    applicationId: applicationData.id,
                    candidateId: applicationData.candidateId,
                    jobId: applicationData.jobId,
                    jobTitle: applicationData.jobTitle,
                    candidateName: applicationData.candidateName,
                    action: 'view_application',
                    autoGenerated: true,
                    timestamp: new Date().toISOString()
                }
            });

            console.log('✅ Auto application notification sent:', response);
            return response;
        } catch (error) {
            console.error('❌ Failed to auto-send application notification:', error);
            return null;
        }
    }

    /**
     * Tự động gửi thông báo chào mừng user mới
     * @param {object} userData - User data
     */
    static async autoNotifyNewUserWelcome(userData) {
        try {
            console.log('🔄 Auto-sending welcome notification...');
            
            const welcomeMessages = {
                'candidate': {
                    title: '🎉 Chào mừng đến với JobBridge!',
                    message: 'Cảm ơn bạn đã đăng ký! Hãy hoàn thiện hồ sơ để tìm được công việc phù hợp nhất.'
                },
                'employer': {
                    title: '🏢 Chào mừng nhà tuyển dụng!',
                    message: 'Cảm ơn bạn đã gia nhập JobBridge! Bắt đầu đăng tin tuyển dụng để tìm ứng viên phù hợp.'
                }
            };

            const message = welcomeMessages[userData.role] || welcomeMessages['candidate'];
            
            const response = await notificationApiService.createNotification({
                recipient_id: userData.id,
                recipient_type: userData.role,
                title: message.title,
                message: message.message,
                type: 'system_announcement',
                sender_type: 'system',
                data: {
                    welcomeType: 'new_user',
                    userRole: userData.role,
                    registrationDate: new Date().toISOString(),
                    autoGenerated: true,
                    action: userData.role === 'candidate' ? 'complete_profile' : 'create_job'
                }
            });

            console.log('✅ Auto welcome notification sent:', response);
            return response;
        } catch (error) {
            console.error('❌ Failed to auto-send welcome notification:', error);
            return null;
        }
    }

    /**
     * Tự động gửi thông báo xác thực email
     * @param {string} userId - User ID
     * @param {string} userRole - User role
     * @param {string} email - User email
     */
    static async autoNotifyEmailVerified(userId, userRole, email) {
        try {
            console.log('🔄 Auto-sending email verification notification...');
            
            const response = await notificationApiService.createNotification({
                recipient_id: userId,
                recipient_type: userRole,
                title: '✅ Email đã được xác thực',
                message: `Email ${email} của bạn đã được xác thực thành công. Tài khoản của bạn hiện đã được kích hoạt đầy đủ.`,
                type: 'account_verification',
                sender_type: 'system',
                data: {
                    verificationType: 'email',
                    email: email,
                    verificationDate: new Date().toISOString(),
                    autoGenerated: true,
                    action: 'explore_app'
                }
            });

            console.log('✅ Auto email verification notification sent:', response);
            return response;
        } catch (error) {
            console.error('❌ Failed to auto-send email verification notification:', error);
            return null;
        }
    }

    /**
     * Tự động gửi thông báo nhắc nhở hàng ngày
     */
    static async autoNotifyDailyReminder() {
        try {
            console.log('🔄 Auto-sending daily reminder...');
            
            const candidateResponse = await notificationApiService.sendSystemNotification({
                recipient_type: 'candidate',
                title: '💼 Cơ hội việc làm mới hôm nay',
                message: 'Hãy khám phá những cơ hội việc làm mới được đăng tuyển hôm nay!',
                type: 'system_announcement',
                data: {
                    reminderType: 'daily_jobs',
                    autoGenerated: true,
                    action: 'browse_jobs',
                    timestamp: new Date().toISOString()
                }
            });

            const employerResponse = await notificationApiService.sendSystemNotification({
                recipient_type: 'employer',
                title: '📊 Theo dõi tin tuyển dụng',
                message: 'Kiểm tra các ứng viên mới và quản lý tin tuyển dụng của bạn.',
                type: 'system_announcement', 
                data: {
                    reminderType: 'daily_management',
                    autoGenerated: true,
                    action: 'manage_jobs',
                    timestamp: new Date().toISOString()
                }
            });

            console.log('✅ Auto daily reminders sent');
            return { candidateResponse, employerResponse };
        } catch (error) {
            console.error('❌ Failed to auto-send daily reminders:', error);
            return null;
        }
    }

    /**
     * Tự động gửi thông báo profile incomplete reminder
     * @param {string} userId - User ID  
     * @param {string} userRole - User role
     */
    static async autoNotifyProfileIncomplete(userId, userRole) {
        try {
            console.log('🔄 Auto-sending profile incomplete reminder...');
            
            const response = await notificationApiService.createNotification({
                recipient_id: userId,
                recipient_type: userRole,
                title: '📝 Hoàn thiện hồ sơ của bạn',
                message: 'Hồ sơ của bạn chưa đầy đủ. Hãy hoàn thiện để tăng cơ hội tìm được việc làm phù hợp!',
                type: 'profile_update',
                sender_type: 'system',
                data: {
                    reminderType: 'profile_incomplete',
                    autoGenerated: true,
                    action: 'complete_profile',
                    timestamp: new Date().toISOString()
                }
            });

            console.log('✅ Auto profile incomplete notification sent:', response);
            return response;
        } catch (error) {
            console.error('❌ Failed to auto-send profile incomplete notification:', error);
            return null;
        }
    }

    /**
     * Thông báo ứng viên nộp đơn (gửi cho employer)
     * @param {string} employerId - ID nhà tuyển dụng
     * @param {string} candidateName - Tên ứng viên
     * @param {string} jobTitle - Tên công việc
     * @param {object} applicationData - Dữ liệu đơn ứng tuyển
     */
    static async autoNotifyJobApplication(employerId, candidateName, jobTitle, applicationData = {}) {
        try {
            console.log('🔄 Auto-sending job application notification...');
            
            const response = await notificationApiService.createNotification({
                recipient_id: employerId,
                recipient_type: 'employer',
                title: '💼 Có đơn ứng tuyển mới!',
                message: `${candidateName} vừa ứng tuyển vào vị trí "${jobTitle}"`,
                type: 'application_received',
                sender_type: 'system',
                data: {
                    candidate_name: candidateName,
                    job_title: jobTitle,
                    application_id: applicationData.application_id,
                    candidate_id: applicationData.candidate_id,
                    action: 'view_application',
                    auto_generated: true,
                    timestamp: new Date().toISOString()
                }
            });

            console.log('✅ Auto job application notification sent:', response);
            return response;
        } catch (error) {
            console.error('❌ Failed to auto-send job application notification:', error);
            return null;
        }
    }

    /**
     * Thông báo trạng thái đơn ứng tuyển (gửi cho candidate) 
     * @param {string} candidateId - ID ứng viên
     * @param {string} status - Trạng thái mới (accepted/rejected/interview)
     * @param {string} jobTitle - Tên công việc
     * @param {object} extraData - Dữ liệu bổ sung
     */
    static async autoNotifyApplicationStatus(candidateId, status, jobTitle, extraData = {}) {
        try {
            console.log('🔄 Auto-sending application status notification...');
            
            const statusMessages = {
                'accepted': {
                    title: '🎉 Chúc mừng!',
                    message: `Bạn đã được chấp nhận cho vị trí "${jobTitle}"`
                },
                'rejected': {
                    title: '😔 Thông báo từ nhà tuyển dụng',
                    message: `Đơn ứng tuyển "${jobTitle}" chưa phù hợp lần này`
                },
                'interview': {
                    title: '📅 Mời phỏng vấn',
                    message: `Bạn được mời phỏng vấn cho vị trí "${jobTitle}"`
                },
                'under_review': {
                    title: '⏳ Đang xem xét',
                    message: `Đơn ứng tuyển "${jobTitle}" đang được xem xét`
                }
            };

            const notification = statusMessages[status] || {
                title: '📬 Cập nhật đơn ứng tuyển',
                message: `Có cập nhật mới cho đơn ứng tuyển "${jobTitle}"`
            };

            const response = await notificationApiService.createNotification({
                recipient_id: candidateId,
                recipient_type: 'candidate',
                title: notification.title,
                message: notification.message,
                type: 'application_status',
                sender_type: 'system',
                data: {
                    status: status,
                    job_title: jobTitle,
                    action: 'view_application_details',
                    auto_generated: true,
                    timestamp: new Date().toISOString(),
                    ...extraData
                }
            });

            console.log('✅ Auto application status notification sent:', response);
            return response;
        } catch (error) {
            console.error('❌ Failed to auto-send application status notification:', error);
            return null;
        }
    }
}

export default JobNotificationHelper;