/**
 * Mock Candidates Data
 * Migrated from features/connect/data/mockCandidates.js
 * Temporary mock data for Connect feature. Replace with API data when available.
 */

const mockCandidates = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    title: "React Native Developer",
    level: "senior",
    experience: "4 năm",
    location: "Hà Nội",
    skills: ["React Native", "TypeScript", "Redux"],
    email: "nguyenvana@example.com",
    phone: "0123456789",
    avatar: null,
    summary: "Experienced React Native developer with 4 years of experience",
    salaryExpectation: "25-30 triệu",
    isActive: true,
    isAvailable: true,
    rating: 4.5,
    cvUrl: null,
    portfolioUrl: null,
  },
  {
    id: 2,
    name: "Trần Thị B",
    title: "Frontend Developer",
    level: "mid",
    experience: "2 năm",
    location: "TP.HCM",
    skills: ["React", "JavaScript", "Tailwind"],
    email: "tranthib@example.com",
    phone: "0987654321",
    avatar: null,
    summary: "Mid-level frontend developer specializing in React",
    salaryExpectation: "15-20 triệu",
    isActive: true,
    isAvailable: true,
    rating: 4.2,
    cvUrl: null,
    portfolioUrl: null,
  },
  {
    id: 3,
    name: "Lê Văn C",
    title: "Backend Developer",
    level: "junior",
    experience: "1 năm",
    location: "Đà Nẵng",
    skills: ["Node.js", "Express", "MongoDB"],
    email: "levanc@example.com",
    phone: "0369852147",
    avatar: null,
    summary: "Junior backend developer with Node.js experience",
    salaryExpectation: "8-12 triệu",
    isActive: true,
    isAvailable: true,
    rating: 3.8,
    cvUrl: null,
    portfolioUrl: null,
  },
  {
    id: 4,
    name: "Phạm Minh D",
    title: "Full Stack Developer",
    level: "mid",
    experience: "3 năm",
    location: "Hà Nội",
    skills: ["React", "Node.js", "PostgreSQL", "Docker"],
    email: "phamminhd@example.com",
    phone: "0741852963",
    avatar: null,
    summary:
      "Full stack developer with strong background in modern web technologies",
    salaryExpectation: "18-25 triệu",
    isActive: true,
    isAvailable: true,
    rating: 4.3,
    cvUrl: null,
    portfolioUrl: null,
  },
  {
    id: 5,
    name: "Hoàng Thị E",
    title: "UI/UX Designer",
    level: "senior",
    experience: "5 năm",
    location: "TP.HCM",
    skills: ["Figma", "Adobe XD", "Sketch", "User Research"],
    email: "hoangthie@example.com",
    phone: "0258147369",
    avatar: null,
    summary:
      "Senior UI/UX designer with extensive experience in mobile and web design",
    salaryExpectation: "20-28 triệu",
    isActive: true,
    isAvailable: true,
    rating: 4.7,
    cvUrl: null,
    portfolioUrl: null,
  },
];

export default mockCandidates;
